version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_REPO_NAME=java-container-repo
      - AWS_ACCOUNT_ID=757367946571
      - AWS_DEFAULT_REGION=ap-south-1
      - IMAGE_TAG=latest
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Running Maven build...
      - mvn clean install

      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME .

      - echo Tagging Docker image...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI:$IMAGE_TAG

      - echo Creating imagedefinitions.json...
      - printf '[{"name":"app-java","imageUri":"%s"}]' $IMAGE_URI:$IMAGE_TAG > imagedefinitions.json

      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
