version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - IMAGE_NAME=757367946571.dkr.ecr.ap-south-1.amazonaws.com/java-container-repo
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 757367946571.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - mvn clean install
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $IMAGE_NAME:$IMAGE_TAG
      - printf '[{"name":"app-java","imageUri":"%s"}]' $IMAGE_NAME:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
